/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddproductRouteImport } from './routes/addproduct'
import { Route as AvailableproductsRouteImport } from './routes/availableproducts'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FoodmenuRouteImport } from './routes/foodmenu'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StockRouteImport } from './routes/stock'
import { Route as TablesRouteImport } from './routes/tables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddproductRoute = AddproductRouteImport.update({
  id: '/addproduct',
  path: '/addproduct',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailableproductsRoute = AvailableproductsRouteImport.update({
  id: '/availableproducts',
  path: '/availableproducts',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodmenuRoute = FoodmenuRouteImport.update({
  id: '/foodmenu',
  path: '/foodmenu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addproduct': typeof AddproductRoute
  '/availableproducts': typeof AvailableproductsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/foodmenu': typeof FoodmenuRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addproduct': typeof AddproductRoute
  '/availableproducts': typeof AvailableproductsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/foodmenu': typeof FoodmenuRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addproduct': typeof AddproductRoute
  '/availableproducts': typeof AvailableproductsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/foodmenu': typeof FoodmenuRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/addproduct'
    | '/availableproducts'
    | '/cart'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/foodmenu'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/staff'
    | '/stock'
    | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/addproduct'
    | '/availableproducts'
    | '/cart'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/foodmenu'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/staff'
    | '/stock'
    | '/tables'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/addproduct'
    | '/availableproducts'
    | '/cart'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/foodmenu'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reports'
    | '/staff'
    | '/stock'
    | '/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddproductRoute: typeof AddproductRoute
  AvailableproductsRoute: typeof AvailableproductsRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  FoodmenuRoute: typeof FoodmenuRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  StaffRoute: typeof StaffRoute
  StockRoute: typeof StockRoute
  TablesRoute: typeof TablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addproduct': {
      id: '/addproduct'
      path: '/addproduct'
      fullPath: '/addproduct'
      preLoaderRoute: typeof AddproductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availableproducts': {
      id: '/availableproducts'
      path: '/availableproducts'
      fullPath: '/availableproducts'
      preLoaderRoute: typeof AvailableproductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foodmenu': {
      id: '/foodmenu'
      path: '/foodmenu'
      fullPath: '/foodmenu'
      preLoaderRoute: typeof FoodmenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddproductRoute: AddproductRoute,
  AvailableproductsRoute: AvailableproductsRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  FoodmenuRoute: FoodmenuRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  StaffRoute: StaffRoute,
  StockRoute: StockRoute,
  TablesRoute: TablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
